trigger:
 - master
pool:
  name: default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  revision: $[counter(variables['Minor'], 1)] 
  nugetVersion: '$(Major).$(Minor).$(revision)'
  nugetProjectName: 'FileAppLogger'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: VSBuild@1
  inputs:
   solution: '$(solution)'
   msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
   platform: '$(buildPlatform)'
   configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'Create NuGet Package'
  inputs:
      command: 'pack'
      packagesToPack: '**/$(nugetProjectName).csproj'
      packDestination: '$(Build.ArtifactStagingDirectory)'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'nugetVersion'
- task: NuGetCommand@2
  inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '7e3d1ac4-1114-44b5-b0dc-923c356739d5'
